# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
#  - echo "Before script section"
  - pwd
  - bash
  - export PATH="/home/adimauro/miniconda37/bin:$PATH"
  - source activate general
  
stages:
  - fetch
  - build
  - test
  
ips:
  stage: fetch
  script:
    - echo "Fetching IPs"
    - python fetch_deps.py
    - python extract_info.py 
  artifacts:
    paths:
      - ips/*
      - sim/*


#after_script:
#  - echo "After script section"
#  - echo "For example you might do some cleanup here"

rtl:
  stage: build
  script:
    - cd sim
    - vsim -c -do CI_build.do
    artifacts:
      paths:
        - ips/*
        - sim/*


sim:
  stage: test
  script:
    - echo "Simulate"
    - cd sim
    - vsim -c -do CI_sim_1.do
