# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - echo "Before script section"
  - source CI_fetch_ips.sh
  - cd ..
  - bash
  - export PATH="/home/adimauro/miniconda37/bin:$PATH"
  - source activate general
  - python extract_info.py 
  

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - echo "Do your build here"
    - cd sim
    - vsim -c -do CI_build.do

test1:
  stage: test
  script:
    - echo "Do a test here"
    - vsim -c -do CI_sim.do

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
